const words = ["HANGMAN", "COLLEGE", "JAVASCRIPT", "CODING", "PROJECT", "TECHNOLOGY", "COMPUTER", "INTELLIGENT", "GAME", "STUDIO", "AWESOME", "WONDERFUL", "BEAUTIFUL", "SPLENDID", 
    "INCREDIBLE", "CHICKEN", "TURKEY", "ALLIGATOR", "GORILLA", "FORTNITE", "MINECRAFT", "ERASER", "PENCIL", "HEADPHONES", "PYTHON", "REACT", "MOUSE", "DOG", "ELEPHANT", "PANTHER", "EAGLE", "FALCON",
    "JAGUAR", "DOLPHIN", "WHALE", "TIGER", "LION", "ARMADILLO", "PELICAN", "RHINO", "GIRAFFE", 
];
